// DO NOT EDIT. This file is auto-generated by Fresh.
// This file should be committed to source control.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/api/proxy.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/api/proxy.ts": $1,
  },
  islands: {},
};

export default manifest;
